apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-0noz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-0noz@sha256:025fd6ec9edd62f3050f3725e804cc78aa4d8c443b4256dbb4e8a5b3e6737618
        name: my-nodejs
        resources: {}
status: {}
